
select FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE MANAGER_ID IN (
	SELECT EMPLOYEE_ID
    FROM EMPLOYEES
    WHERE FIRST_NAME = 'Payam');
    
select FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN (
	SELECT JOB_ID
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 169);

SELECT
	E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM EMPLOYEES AS E
WHERE E.SALARY > (
	SELECT SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEES.LAST_NAME = 'Ozer');
    
SELECT 
	DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, DEPARTMENTS.MANAGER_ID, DEPARTMENTS.LOCATION_ID
FROM EMPLOYEES JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, DEPARTMENTS.MANAGER_ID, DEPARTMENTS.LOCATION_ID
HAVING min(SALARY) > 8000;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM EMPLOYEES
WHERE 
EMPLOYEES.DEPARTMENT_ID = (
SELECT DEPARTMENTS.DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENTS.DEPARTMENT_NAME = 'Marketing');
SET SQL_SAFE_UPDATES = 1;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE EMPLOYEES.DEPARTMENT_ID IN (
	SELECT DEPARTMENTS.DEPARTMENT_ID 
	FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
	WHERE EMPLOYEES.FIRST_NAME LIKE '%J%' OR EMPLOYEES.LAST_NAME LIKE '%J%'	
)
HAVING SALARY > ( 
	SELECT AVG(SALARY)
	FROM EMPLOYEES);
    
    
DELIMITER //	
CREATE TRIGGER HELLO
	BEFORE DELETE
    ON EMPLOYEES FOR EACH ROW 
BEGIN

END;

DELIMITER;




